### ISSUE TITLE
Docker machine panics when 'ls' is run with invalid filter params

### ISSUE THREAD

**Issue by saurabh-g** [docker/machine#1502]
Steps to reproduce:
`docker-machine ls --filter random`

Expected Output:
```
NAME   ACTIVE   DRIVER   STATE   URL   SWARM
```
Actual Output:
```
panic: runtime error: index out of range

goroutine 16 [running]:
runtime.panic(0x6a79a0, 0xaf6cdc)
	/usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/docker/machine/commands.parseFilters(0x208caa910, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/machine/commands/ls.go:90 +0x6a1
github.com/docker/machine/commands.cmdLs(0x208c3c240)
	/go/src/github.com/docker/machine/commands/ls.go:23 +0xc2
github.com/codegangsta/cli.Command.Run(0x752eb0, 0x2, 0x0, 0x0, 0x767ef0, 0xd, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0xeb2
github.com/codegangsta/cli.(*App).Run(0x208c12340, 0x208bf6000, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xaea
main.main()
	/go/src/github.com/docker/machine/main.go:114 +0x639

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
	/usr/src/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
	/usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
	/usr/src/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
	/usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
	/usr/src/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
	/usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]:
os/signal.loop()
	/usr/src/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/src/go/src/pkg/os/signal/signal_unix.go:27 +0x32
```

**Comment by ericsage** [comment]
I think there should be an explicit error here since the syntax is incorrect.

**Comment by dgageot** [comment]
Fixed. It'll show `Unsupported filter syntax.`

**Comment by ricejasonf** [comment]
There still appear to be problems with this. I expect that the syntax be considered valid, but I still get the panic:
```
docker-machine ls --filter "label=cppdock_build"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/docker/machine/commands.matchesLabel(0xc4201887e0, 0xc42018f550, 0x1, 0x1, 0xc42018ba01)
	/go/src/github.com/docker/machine/commands/ls.go:324 +0x349
github.com/docker/machine/commands.filterHost(0xc4201887e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/machine/commands/ls.go:244 +0x149
github.com/docker/machine/commands.filterHosts(0xc4201aa1a0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/machine/commands/ls.go:219 +0x179
github.com/docker/machine/commands.cmdLs(0x15400e0, 0xc4201aa120, 0x153ee80, 0xc4201a2910, 0x0, 0x0)
	/go/src/github.com/docker/machine/commands/ls.go:88 +0x1f1
github.com/docker/machine/commands.runCommand.func1(0xc4202a25a0)
	/go/src/github.com/docker/machine/commands/commands.go:163 +0x45a
github.com/docker/machine/vendor/github.com/codegangsta/cli.Command.Run(0x1416e69, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x142109b, 0xd, 0x0, ...)
	/go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/command.go:137 +0x7c2
github.com/docker/machine/vendor/github.com/codegangsta/cli.(*App).Run(0xc4202a2240, 0xc4200b2000, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/app.go:175 +0x864
main.main()
	/go/src/github.com/docker/machine/cmd/docker-machine/machine.go:163 +0xa1f
```

If I use the filter format with the value `--format "label=cppdock_build=1" it works.
```
docker-machine ls --filter "label=cppdock_build=1"
NAME    ACTIVE   DRIVER      STATE     URL                       SWARM   DOCKER     ERRORS
aws01   *        amazonec2   Running   tcp://REDACTED:2376           v18.09.7   
```

Version Info:
`docker-machine version 0.16.0, build 702c267f`
