### ISSUE TITLE
"Error creating machine: Invalid hostname specified" error when the name has _ character

### ISSUE THREAD

**Issue by ksasi** [docker/machine#1778]
Hi,

We are receiving error if the name has an underscore character. Below are the details : 

bash-3.2$ docker-machine create --driver=virtualbox a_
Error creating machine: Invalid hostname specified
You will want to check the provider to make sure the machine and associated resources were properly removed.
bash-3.2$ docker-machine create --driver=virtualbox a_1
Error creating machine: Invalid hostname specified
You will want to check the provider to make sure the machine and associated resources were properly removed.
bash-3.2$ docker-machine create --driver=virtualbox 1_a
Error creating machine: Invalid hostname specified
You will want to check the provider to make sure the machine and associated resources were properly removed.

Thanks and Regards,
Sasikanth

**Comment by oolongtea** [comment]
Looks like the regex validating the name and the valid characters are [found in `host.go`](https://github.com/docker/machine/blob/0c96ea0de292ae40cdb54fa4346988b72262a316/libmachine/host.go#L27), which do not include underscore. 

More details on valid hostnames can be found at [this wiki page](https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names).

**Comment by dgageot** [comment]
Closing. This is fixed in 0.5.0

**Comment by papb** [comment]
It seems underscore is still not allowed: https://github.com/docker/machine/blob/b170508bf44c3405e079e26d5fdffe35a64c6972/libmachine/host/host.go#L24
