### ISSUE TITLE
docker-machine start hangs on Testing TCP connection with bad localhost

### ISSUE THREAD

**Issue by dblock** [docker/machine#1946]
This one was my fault, but docker-machine could probably do a better job at reporting a problem here, `docker-machine start dusty` was hanging. Using `--debug` showed:

```
Testing TCP connection to: localhost:64623
Testing TCP connection to: localhost:64623
Testing TCP connection to: localhost:64623
...
```

I had the following in my `/etc/hosts`

```
0 localhost
```

This came from a hosts file attempting to be very conservative about ad blocking :)

Failure to resolve the host name should be a different error here.

**Comment by nathanleclaire** [comment]
We default to `127.0.0.1` for VirtualBox now.  Not the best solution, but it should solve this issue.

**Comment by dblock** [comment]
That's fine @nathanleclaire but I think my bug is more about the error than about the actual fix. The DNS entry that doesn't resolve will continue giving you no information as above, no?

**Comment by nathanleclaire** [comment]
@dblock We removed the TCP check as well but, what error would you expect to see in such a situation?

**Comment by dblock** [comment]
In this case a different error for hostname cannot be resolved vs. connection timed out (port closed, etc.)
