### ISSUE TITLE
(Lack of) shared folders support using vmwarefusion driver

### ISSUE THREAD

**Issue by dallas** [docker/machine#1995]
Brand new MacBook Pro with El Capitan installed version 10.11 (15A284).
VMware Fusion version 8.0.1 (3094680).
Docker version 1.8.3, build f4bf5c7—installed via `brew install docker`.
docker-machine version 0.4.1 (HEAD)—installed via `brew install docker-machine`.
docker-compose version: 1.4.2—installed via `brew install docker-compose`.
Boot2Docker version 1.8.3, build master : af8b089 - Mon Oct 12 18:56:54 UTC 2015—I'm not sure how this is installed.

I had initially downloaded and installed the Docker Toolkit with VirtualBox and then later added VMware Fusion at which point I completely uninstalled Docker (using this script: https://github.com/docker/toolbox/blob/master/osx/uninstall.sh) and VirtualBox (by manual file deletion) and then reinstalled the Docker tools I needed via Homebrew.

Inside `docker-machine ssh dev`:
```
docker@dev:~$ ls -la /Users/dallas/Code/church-donation/
total 0
drwxr-xr-x    2 root     root            40 Oct 16 15:17 ./
drwxr-xr-x    3 root     root            60 Oct 16 15:17 ../
```
should have these files:
```
dallas > ~ > Code > church-donation > tree -aL 1
.
├── .dockerignore
├── .git
├── .gitignore
├── .yo-rc.json
├── Dockerfile
├── LICENSE
├── app
├── bin
├── bower.json
├── docker-compose.yml
├── gulpfile.coffee
├── package.json
├── src
├── test
├── webpack.config.coffee
└── webpack.config.mine.coffee

5 directories, 11 files
```

```
 dallas > ~ > Code > church-donation > df -h
Filesystem      Size   Used  Avail Capacity  iused     ifree %iused  Mounted on
/dev/disk1     931Gi  125Gi  805Gi    14% 32835229 211140481   13%   /
devfs          180Ki  180Ki    0Bi   100%      623         0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%        0         0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%        0         0  100%   /home
```

CC @frapposelli

**Comment by frapposelli** [comment]
@dallas can you run a `df -h` inside the boot2docker vm? that will tell if shared folders are running or not

**Comment by dallas** [comment]
Oh, yeah. Sorry!

```
docker@dev:~$ df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                   896.5M    115.2M    781.3M  13% /
tmpfs                   498.0M     64.0K    498.0M   0% /dev/shm
/dev/sda1                18.2G      1.3G     16.0G   7% /mnt/sda1
cgroup                  498.0M         0    498.0M   0% /sys/fs/cgroup
vmhgfs-fuse             930.7G    125.3G    805.4G  13% /mnt/hgfs
/dev/sda1                18.2G      1.3G     16.0G   7% /mnt/sda1/var/lib/docker/aufs
none                     18.2G      1.3G     16.0G   7% /mnt/sda1/var/lib/docker/aufs/mnt/d368e8bb067237161cbc38f0da2876c421e98a744a2d7bfabd72b93fb7b3a819
none                     18.2G      1.3G     16.0G   7% /mnt/sda1/var/lib/docker/aufs/mnt/f236ff7a1f14b6f98053416864194cb38ba4ccef41ffd5532a4cf8beb039a3a0
df: /var/run/docker/netns/d368e8bb0672: Permission denied
df: /var/run/docker/netns/f236ff7a1f14: Permission denied
```

**Comment by frapposelli** [comment]
@dallas your issue stems from a misaligned release between `docker-machine` and `boot2docker`, `boot2docker` is fine but you should compile and run `docker-machine` from the tip of `master` as you're missing this critical commit in `v0.4.1`: c3ed882b7612124ca8f050ff0275660082a41651.

**Comment by dallas** [comment]
Oh. Can I do that using homebrew or should I use one of the release downloads?

**Comment by frapposelli** [comment]
I don't think there is a nightly build available, paging @ehazlett and @nathanleclaire for that.

Best option would be to just clone the repo and compile it with `make remote`, that doesn't require shared folders to work.

**Comment by dallas** [comment]
Okay, I will give that a shot and post back here with the success or failure.

**Comment by dallas** [comment]
I'm sorry, could you provide slightly more instructions on how to build it? Am I supposed to build it inside of a VM, inside of a docker container in a VM? I tried `make remote` on my local system inside the root folder of the project and first it complained that I didn't have `go` installed. So I ran `brew install go` and set my `GOPATH` and tried `make remote` again, which immediately exited without any output. Thank you for all of your help!

**Comment by frapposelli** [comment]
@dallas see https://github.com/docker/machine/blob/master/CONTRIBUTING.md for instructions on how to compile machine from source.

**Comment by nathanleclaire** [comment]
Chiming in to say there's a possibility `make remote` might be busted due to recent `Makefile` changes.  cc @dmp42 can you confirm it works please?

**Comment by dallas** [comment]
I'll take a look at the CONTRIBUTING file and give it another shot, @frapposelli & @nathanleclaire. I'll be out of the country (and away from my computer) all next week, so I won't be able to try out other things during that time. Thanks for your help, guys!

**Comment by dallas** [comment]
Just kidding—I'm not going to have adequate time before I leave. I'll check back in on this issue in a week. Thanks again!

**Comment by aventurella** [comment]
@dallas I was getting the same issue under OSX 10.10. found your issue #641, then found this issue

`TL;DR: building the latest version did succeed for me in being able to access shared folders.`

**The Details**

Running `vmware fusion 8`
Followed the instructions in `CONTRIBUTING`

Built the following version:
docker-machine version 0.5.0-rc1 (43543d1)

```
make build
make install
```

executed the following commands:

```
docker-machine create -d vmwarefusion fusion
eval "$(docker-machine env fusion)"
docker run -it -v "/Users/aventurella/github:/root/github" debian:latest /bin/bash

... inside the container...

# cd /root/github
# ls 
```
**SUCCESS!** everything is there.

**Comment by frapposelli** [comment]
@aventurella :+1:

**Comment by dmp42** [comment]
@dallas (cc @nathanleclaire) `make remote` is no longer a target. @frapposelli pointed to the correct document for information on how to build.
Let us know how that work for you.

**Comment by nathanleclaire** [comment]
Since I believe this issue is resolved using tip from both boot2docker and docker-machine, I'm closing this issue.  Thanks @frapposelli and @dallas feel free to let us know if you encounter any more issues.

**Comment by joeczucha** [comment]
Just to confirm that this bug still exists in the version of docker-machine installed by homebrew... building from source worked though. Thanks all.

**Comment by samy100** [comment]
Confirmed here as well OSX 10.9 and VMware Fusion 7.1.3 installed via toolbox.
