### ISSUE TITLE
create command fails, using homebrew-installed vmware fusion

### ISSUE THREAD

**Issue by derhuerst** [docker/machine#2227]
I use VMWare Fusion, installed by `brew cask install vmware-fusion`. The `vmrun` CLI tool is in my path.

The `docker-machine create …` script silently fails, because `/Applications/VMware Fusion.app/Contents/Library/vmrun` does not exist.

Please adjust the script to accept a homebrew-installed VMWare Fusion. #1434 might be related.

**Comment by derhuerst** [comment]
This works as a temporary fix for me:

```shell
# find out where vmrun is installed
which vmrun

# copy the path until `.app`

# symlink the `.app` into `/Applications`
ln -s pathToAppBundleHere "/Applications/VMware Fusion.app"
```

**Comment by mafrosis** [comment]
Same here - manually adding a symlink fixed it:

   ln -s /opt/homebrew-cask/Caskroom/vmware-fusion6/6.0.5-2209127/VMware\ Fusion.app /Applications

**Comment by frapposelli** [comment]
This should've been fixed in the latest `0.5.0` version, are you guys using the latest released version of `docker-machine` ?

**Comment by mafrosis** [comment]
> docker-machine -v
    docker-machine version 0.5.0 (HEAD)

**Comment by dgageot** [comment]
Hi @derhuerst, @mafrosis, @frapposelli is there still an issue?

**Comment by derhuerst** [comment]
@dgageot It's fixed for me.

**Comment by frapposelli** [comment]
@dgageot this can be closed
