### ISSUE TITLE
'docker-machine config' certPath differs from 'docker-machine env' certPath

### ISSUE THREAD

**Issue by michaelharrer** [docker/machine#3909]
## Issue
I used docker-machine config <machinename> to init my swarm until now.
` docker $(docker-machine config $MANAGER) swarm init --advertise-addr $(docker-machine ip $MANAGER):2377 --listen-addr $(docker-machine ip $MANAGER)`

Unfortunately this does not work anymore (dont know the exact breaking version, but it did work for docker 1.12.2 (beta))

It will now result in following error: 
> ---> Create manager manager1
> Running pre-create checks...
> Creating machine...
> ...
> Docker is up and running!
> To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env manager1
> could not read CA certificate "\"/Users/michaelh/.docker/machine/certs/ca.pem\"": open "/Users/michaelh/.docker/machine/certs/ca.pem": no such file or directory
> 

I checked the output of docker-machine env <nodename> vs the used docker-machine config <nodename>

```
docker-machine env manager1
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.106:2376"
export DOCKER_CERT_PATH="/Users/michaelh/.docker/machine/machines/manager1"
export DOCKER_MACHINE_NAME="manager1"
export DOCKER_API_VERSION="1.25"
```

vs 

```
docker-machine config manager1
--tlsverify
--tlscacert="/Users/michaelh/.docker/machine/certs/ca.pem"
--tlscert="/Users/michaelh/.docker/machine/certs/cert.pem"
--tlskey="/Users/michaelh/.docker/machine/certs/key.pem"
-H=tcp://192.168.99.106:2376
```

As you can see the tlscert path is different from the docker cert path. When I use eval $(docker-machine env <nodename>) before, all works as intended.

### Docker-machine:
Version: 0.9.0-rc1
Build ed849a7

### Docker:
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      darwin/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 17:40:58 2016
 OS/Arch:             linux/amd64
 Experimental:        true

**Comment by nathanleclaire** [comment]
I do seem to recall this coming up before and I'm fairly certain it's a valid bug.  I'll have to look into fixing, thanks for the report.

**Comment by nathanleclaire** [comment]
It's fixed now (will land in 0.9.0) but, I'm still a bit confused by the error message, /Users/michaelh/.docker/machine/certs/ca.pem should still be present

**Comment by michaelharrer** [comment]
It IS still present. This was what led me into the wrong direction at first.
Thanks very much for the quick fix!

**Comment by marcosnils** [comment]
> It's fixed now (will land in 0.9.0) but, I'm still a bit confused by the error message, /Users/michaelh/.docker/machine/certs/ca.pem should still be present...

@nathanleclaire  path is present indeed, the problem is that machine seems to be adding some quotes / escapes characters incorrectly when printing the corresponding flags. 

i.e:
```
marcos@marcos-xps:~$ docker $(docker-machine config lala) ps
could not read CA certificate "\"/home/marcos/.docker/machine/certs/ca.pem\"": open "/home/marcos/.docker/machine/certs/ca.pem": no such file or directory
marcos@marcos-xps:~$ ls -la /home/marcos/.docker/machine/certs/ca.pem
-rw-rw-r-- 1 marcos marcos 1038 dic 22 00:39 /home/marcos/.docker/machine/certs/ca.pem
```

As you can see, the cert file exists but `config` seems to be adding incorrect quotes and escape character to the command output

This is what I get if I run `docker-machine config lala` only:


```
marcos@marcos-xps:~$ docker-machine config lala
--tlsverify
--tlscacert="/home/marcos/.docker/machine/certs/ca.pem"
--tlscert="/home/marcos/.docker/machine/certs/cert.pem"
--tlskey="/home/marcos/.docker/machine/certs/key.pem"
-H=tcp://192.168.99.101:2376
```

Hope this helps to better understand this issue.

**Comment by nathanleclaire** [comment]
@marcosnils I can dupe, will take a look

**Comment by marcosnils** [comment]
Thx. Btw, we finally did the machine driver for pwd ;)

https://github.com/franela/docker-machine-driver-pwd


sent from mobile

**Comment by nathanleclaire** [comment]
Cool 😎

**Comment by nathanleclaire** [comment]
Argh, seems to be an issue with `docker`'s argument parsing.  With 1.12.5 it works fine, with 1.13.0-rc4 it fails.

**Comment by nathanleclaire** [comment]
https://github.com/docker/docker/issues/29761 to track what's happening on docker/docker side
